// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service reads from and writes to the system clipboard.
 * Uses xclip, xsel, or wl-paste/wl-copy on Linux (tries each in order).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CopyFromForeground sends Ctrl+C to the currently focused window via xdotool,
 * then waits 150 ms for the clipboard to be populated.
 * Best-effort: if xdotool is not installed, logs a warning and returns nil.
 * @returns {$CancellablePromise<void>}
 */
export function CopyFromForeground() {
    return $Call.ByID(239340991);
}

/**
 * PasteToForeground sends a Ctrl+V keystroke to the currently focused window.
 * Best-effort: if xdotool is not installed, logs a warning and returns nil.
 * @returns {$CancellablePromise<void>}
 */
export function PasteToForeground() {
    return $Call.ByID(2319679526);
}

/**
 * Read returns the current clipboard text content.
 * Tries xclip → xsel → wl-paste. Returns a clear error if none are available.
 * @returns {$CancellablePromise<string>}
 */
export function Read() {
    return $Call.ByID(52599179);
}

/**
 * Write sets the clipboard text content.
 * Tries xclip → xsel → wl-copy. Returns a clear error if none are available.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function Write(text) {
    return $Call.ByID(608683786, text);
}
