// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClaudeCodeStatus is what KeyLint can tell about the locally installed CLI.
 * It deliberately carries no account details: `claude auth status` also prints
 * the user's email and organisation, and none of that is KeyLint's business.
 */
export class ClaudeCodeStatus {
    /**
     * Creates a new ClaudeCodeStatus instance.
     * @param {Partial<ClaudeCodeStatus>} [$$source = {}] - The source object to create the ClaudeCodeStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("loggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loggedIn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeCodeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeCodeStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeCodeStatus(/** @type {Partial<ClaudeCodeStatus>} */($$parsedSource));
    }
}

/**
 * ModelInfo is one entry in a model picker.
 */
export class ModelInfo {
    /**
     * Creates a new ModelInfo instance.
     * @param {Partial<ModelInfo>} [$$source = {}] - The source object to create the ModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo(/** @type {Partial<ModelInfo>} */($$parsedSource));
    }
}

/**
 * ModelList is a picker's contents plus where they came from.
 */
export class ModelList {
    /**
     * Creates a new ModelList instance.
     * @param {Partial<ModelList>} [$$source = {}] - The source object to create the ModelList.
     */
    constructor($$source = {}) {
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ModelInfo[]}
             */
            this["models"] = [];
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelList}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField0_0($$parsedSource["models"]);
        }
        return new ModelList(/** @type {Partial<ModelList>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
