// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClaudeCodeStatus is what KeyLint can tell about the locally installed CLI.
 * It deliberately carries no account details: `claude auth status` also prints
 * the user's email and organisation, and none of that is KeyLint's business.
 */
export class ClaudeCodeStatus {
    /**
     * Creates a new ClaudeCodeStatus instance.
     * @param {Partial<ClaudeCodeStatus>} [$$source = {}] - The source object to create the ClaudeCodeStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("loggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loggedIn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeCodeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeCodeStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeCodeStatus(/** @type {Partial<ClaudeCodeStatus>} */($$parsedSource));
    }
}
