// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * simulateService exposes SimulateShortcut to the frontend (used by dev-tools button).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SetShortcutPaused temporarily disables shortcut detection (e.g. while recording a new shortcut in settings).
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetShortcutPaused(paused) {
    return $Call.ByID(2045995901, paused);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SimulateShortcut() {
    return $Call.ByID(2906140003);
}
