// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppPreset maps a source application name to a preferred document type.
 * Mirrors settings.AppPreset — kept separate to avoid circular imports.
 */
export class AppPreset {
    /**
     * Creates a new AppPreset instance.
     * @param {Partial<AppPreset>} [$$source = {}] - The source object to create the AppPreset.
     */
    constructor($$source = {}) {
        if (!("sourceApp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceApp"] = "";
        }
        if (!("documentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppPreset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppPreset(/** @type {Partial<AppPreset>} */($$parsedSource));
    }
}

/**
 * PyramidizeRequest is the RPC request for the main Pyramidize call.
 */
export class PyramidizeRequest {
    /**
     * Creates a new PyramidizeRequest instance.
     * @param {Partial<PyramidizeRequest>} [$$source = {}] - The source object to create the PyramidizeRequest.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("documentType" in $$source)) {
            /**
             * "auto"|"email"|"wiki"|"powerpoint"|"memo"
             * @member
             * @type {string}
             */
            this["documentType"] = "";
        }
        if (!("communicationStyle" in $$source)) {
            /**
             * "professional"|"casual"|"concise"|"detailed"|"persuasive"|"neutral"|"diplomatic"|"direct"
             * @member
             * @type {string}
             */
            this["communicationStyle"] = "";
        }
        if (!("relationshipLevel" in $$source)) {
            /**
             * "close"|"professional"|"authority"|"public"
             * @member
             * @type {string}
             */
            this["relationshipLevel"] = "";
        }
        if (!("customInstructions" in $$source)) {
            /**
             * optional, not persisted
             * @member
             * @type {string}
             */
            this["customInstructions"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * optional override: "claude"|"openai"|"ollama" — falls back to settings.ActiveProvider
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * optional override, e.g. "claude-sonnet-4-6" — falls back to provider default
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("promptVariant" in $$source)) {
            /**
             * 0 = latest (default), 1 = v1, 2 = v2, etc.
             * @member
             * @type {number}
             */
            this["promptVariant"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PyramidizeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PyramidizeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PyramidizeRequest(/** @type {Partial<PyramidizeRequest>} */($$parsedSource));
    }
}

/**
 * PyramidizeResult is the RPC response from the main Pyramidize call.
 */
export class PyramidizeResult {
    /**
     * Creates a new PyramidizeResult instance.
     * @param {Partial<PyramidizeResult>} [$$source = {}] - The source object to create the PyramidizeResult.
     */
    constructor($$source = {}) {
        if (!("documentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentType"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("fullDocument" in $$source)) {
            /**
             * first line = subject/title
             * @member
             * @type {string}
             */
            this["fullDocument"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["headers"] = [];
        }
        if (!("qualityScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["qualityScore"] = 0;
        }
        if (!("qualityFlags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["qualityFlags"] = [];
        }
        if (!("appliedRefinement" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["appliedRefinement"] = false;
        }
        if (!("refinementWarning" in $$source)) {
            /**
             * non-empty if still below threshold after retry
             * @member
             * @type {string}
             */
            this["refinementWarning"] = "";
        }
        if (!("detectedType" in $$source)) {
            /**
             * only set when AUTO was used
             * @member
             * @type {string}
             */
            this["detectedType"] = "";
        }
        if (!("detectedLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detectedLang"] = "";
        }
        if (!("detectedConfidence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["detectedConfidence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PyramidizeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PyramidizeResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        if ("qualityFlags" in $$parsedSource) {
            $$parsedSource["qualityFlags"] = $$createField5_0($$parsedSource["qualityFlags"]);
        }
        return new PyramidizeResult(/** @type {Partial<PyramidizeResult>} */($$parsedSource));
    }
}

/**
 * RefineGlobalRequest is the RPC request for a full-canvas AI revision.
 */
export class RefineGlobalRequest {
    /**
     * Creates a new RefineGlobalRequest instance.
     * @param {Partial<RefineGlobalRequest>} [$$source = {}] - The source object to create the RefineGlobalRequest.
     */
    constructor($$source = {}) {
        if (!("fullCanvas" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fullCanvas"] = "";
        }
        if (!("originalText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalText"] = "";
        }
        if (!("instruction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instruction"] = "";
        }
        if (!("documentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentType"] = "";
        }
        if (!("communicationStyle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["communicationStyle"] = "";
        }
        if (!("relationshipLevel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relationshipLevel"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefineGlobalRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefineGlobalRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefineGlobalRequest(/** @type {Partial<RefineGlobalRequest>} */($$parsedSource));
    }
}

/**
 * RefineGlobalResult is the RPC response for a full-canvas AI revision.
 */
export class RefineGlobalResult {
    /**
     * Creates a new RefineGlobalResult instance.
     * @param {Partial<RefineGlobalResult>} [$$source = {}] - The source object to create the RefineGlobalResult.
     */
    constructor($$source = {}) {
        if (!("newCanvas" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["newCanvas"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefineGlobalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefineGlobalResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefineGlobalResult(/** @type {Partial<RefineGlobalResult>} */($$parsedSource));
    }
}

/**
 * SpliceRequest is the RPC request for rewriting a selected canvas section.
 */
export class SpliceRequest {
    /**
     * Creates a new SpliceRequest instance.
     * @param {Partial<SpliceRequest>} [$$source = {}] - The source object to create the SpliceRequest.
     */
    constructor($$source = {}) {
        if (!("fullCanvas" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fullCanvas"] = "";
        }
        if (!("originalText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalText"] = "";
        }
        if (!("selectedText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selectedText"] = "";
        }
        if (!("instruction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instruction"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpliceRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpliceRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpliceRequest(/** @type {Partial<SpliceRequest>} */($$parsedSource));
    }
}

/**
 * SpliceResult is the RPC response for rewriting a selected canvas section.
 */
export class SpliceResult {
    /**
     * Creates a new SpliceResult instance.
     * @param {Partial<SpliceResult>} [$$source = {}] - The source object to create the SpliceResult.
     */
    constructor($$source = {}) {
        if (!("rewrittenSection" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rewrittenSection"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpliceResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpliceResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpliceResult(/** @type {Partial<SpliceResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
