// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service implements the Pyramidize RPC methods exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelOperation cancels the current in-flight Pyramidize, RefineGlobal, or Splice
 * call. Safe to call when nothing is running (no-op).
 * @returns {$CancellablePromise<void>}
 */
export function CancelOperation() {
    return $Call.ByID(2489015650);
}

/**
 * CaptureSourceApp captures the current foreground window before the clipboard grab.
 * Called from main.go when the global hotkey fires, before any clipboard operation.
 * @returns {$CancellablePromise<void>}
 */
export function CaptureSourceApp() {
    return $Call.ByID(1413905145);
}

/**
 * DeleteAppPreset removes an app preset by source app name (case-insensitive).
 * @param {string} sourceApp
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAppPreset(sourceApp) {
    return $Call.ByID(4055448976, sourceApp);
}

/**
 * GetAppPresets returns all saved source-app → doc-type presets from settings.
 * @returns {$CancellablePromise<$models.AppPreset[]>}
 */
export function GetAppPresets() {
    return $Call.ByID(3288329060).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetQualityThreshold returns the configured quality threshold, defaulting to 0.65.
 * @returns {$CancellablePromise<number>}
 */
export function GetQualityThreshold() {
    return $Call.ByID(337443021);
}

/**
 * GetSourceApp returns the captured source app name so the frontend can display
 * the detection indicator and look up a saved app preset.
 * @returns {$CancellablePromise<string>}
 */
export function GetSourceApp() {
    return $Call.ByID(985173551);
}

/**
 * Pyramidize is the main RPC: detects the document type (if AUTO), generates the
 * foundation document, and applies a refinement pass if the quality score is below
 * the configured threshold.
 * @param {$models.PyramidizeRequest} req
 * @returns {$CancellablePromise<$models.PyramidizeResult>}
 */
export function Pyramidize(req) {
    return $Call.ByID(1267468009, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RefineGlobal applies a user instruction to the full canvas document.
 * @param {$models.RefineGlobalRequest} req
 * @returns {$CancellablePromise<$models.RefineGlobalResult>}
 */
export function RefineGlobal(req) {
    return $Call.ByID(296035873, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SendBack writes text to the system clipboard and pastes it back into the
 * captured source application window.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SendBack(text) {
    return $Call.ByID(4139008126, text);
}

/**
 * SetAppPreset saves or updates an app preset matched by SourceApp name (case-insensitive).
 * @param {$models.AppPreset} preset
 * @returns {$CancellablePromise<void>}
 */
export function SetAppPreset(preset) {
    return $Call.ByID(2260797659, preset);
}

/**
 * SetQualityThreshold saves the quality threshold. Value must be in [0, 1].
 * @param {number} v
 * @returns {$CancellablePromise<void>}
 */
export function SetQualityThreshold(v) {
    return $Call.ByID(218741417, v);
}

/**
 * Splice rewrites a selected section of the canvas according to a user instruction.
 * @param {$models.SpliceRequest} req
 * @returns {$CancellablePromise<$models.SpliceResult>}
 */
export function Splice(req) {
    return $Call.ByID(2632758783, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AppPreset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PyramidizeResult.createFrom;
const $$createType3 = $models.RefineGlobalResult.createFrom;
const $$createType4 = $models.SpliceResult.createFrom;
