// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstallResult is returned by DownloadAndInstall to indicate the outcome.
 * On Windows, RestartRequired is true because the NSIS installer needs the app to exit.
 */
export class InstallResult {
    /**
     * Creates a new InstallResult instance.
     * @param {Partial<InstallResult>} [$$source = {}] - The source object to create the InstallResult.
     */
    constructor($$source = {}) {
        if (!("restart_required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restart_required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallResult(/** @type {Partial<InstallResult>} */($$parsedSource));
    }
}

/**
 * UpdateInfo is returned to the frontend to describe whether an update is available.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("is_available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_available"] = false;
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("release_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_url"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}
