// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service checks for updates and can apply them using platform-specific strategies.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate fetches the GitHub Releases API and finds the best available update.
 * 
 * Dev builds (0.0.0-pr.N, 0.0.0-main) never get an answer here: at version
 * 0.0.0 every release would look like an update, forever. They are served by
 * ListDevBuilds instead, which knows where they came from.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2035259492).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DownloadAndInstall fetches the release asset for the current platform, saves it
 * to a temp file, and delegates to the platform-specific installer.
 * On Windows this launches the NSIS setup and returns InstallResult{RestartRequired: true}.
 * On Linux this applies the binary in-place via selfupdate.
 * @returns {$CancellablePromise<$models.InstallResult>}
 */
export function DownloadAndInstall() {
    return $Call.ByID(1125161478).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetBuildIdentity tells the frontend whether it is running a dev build and
 * which one. No network call.
 * @returns {$CancellablePromise<$models.BuildIdentity>}
 */
export function GetBuildIdentity() {
    return $Call.ByID(3907112600).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetVersion returns the current application version.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(4045591078);
}

/**
 * InstallDevBuild downloads and installs a dev-channel build by tag, through
 * the same path as a normal update. Only dev tags are accepted, and only
 * with developer options on or from a dev build.
 * @param {string} tag
 * @returns {$CancellablePromise<$models.InstallResult>}
 */
export function InstallDevBuild(tag) {
    return $Call.ByID(2953585996, tag).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * InstallLatestRelease installs the newest real release on the effective
 * update channel, whatever version is running — the way back from a dev
 * build, which the normal update check deliberately ignores.
 * @returns {$CancellablePromise<$models.InstallResult>}
 */
export function InstallLatestRelease() {
    return $Call.ByID(2499356255).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListDevBuilds lists the dev-channel builds — main first, then open PRs,
 * newest PR first — and says whether the running PR build has been orphaned.
 * force skips the one-minute cache, as a Refresh button wants; it never
 * skips a rate-limit back-off.
 * @param {boolean} force
 * @returns {$CancellablePromise<$models.DevChannel>}
 */
export function ListDevBuilds(force) {
    return $Call.ByID(3149967204, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetQuitFunc sets the callback invoked after launching the installer on Windows.
 * The callback should wait briefly (for the frontend to display a message) then quit the app.
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetQuitFunc(fn) {
    return $Call.ByID(1352960079, fn);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $models.InstallResult.createFrom;
const $$createType2 = $models.BuildIdentity.createFrom;
const $$createType3 = $models.DevChannel.createFrom;
