// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service checks for updates and can apply them using platform-specific strategies.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate fetches the GitHub Releases API and finds the best available update.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2035259492).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DownloadAndInstall fetches the release asset for the current platform, saves it
 * to a temp file, and delegates to the platform-specific installer.
 * On Windows this launches the NSIS setup and returns InstallResult{RestartRequired: true}.
 * On Linux this applies the binary in-place via selfupdate.
 * @returns {$CancellablePromise<$models.InstallResult>}
 */
export function DownloadAndInstall() {
    return $Call.ByID(1125161478).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetVersion returns the current application version.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(4045591078);
}

/**
 * SetQuitFunc sets the callback invoked after launching the installer on Windows.
 * The callback should wait briefly (for the frontend to display a message) then quit the app.
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetQuitFunc(fn) {
    return $Call.ByID(1352960079, fn);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $models.InstallResult.createFrom;
