// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service checks for updates and can apply them in-place using minio/selfupdate.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate fetches the GitHub Releases API and finds the best available update.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2035259492).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DownloadAndInstall fetches the binary for the current platform and replaces the running exe.
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAndInstall() {
    return $Call.ByID(1125161478);
}

/**
 * GetVersion returns the current application version.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(4045591078);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
