// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppPreset maps a source application name to a preferred document type for Pyramidize.
 */
export class AppPreset {
    /**
     * Creates a new AppPreset instance.
     * @param {Partial<AppPreset>} [$$source = {}] - The source object to create the AppPreset.
     */
    constructor($$source = {}) {
        if (!("sourceApp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceApp"] = "";
        }
        if (!("documentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppPreset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppPreset(/** @type {Partial<AppPreset>} */($$parsedSource));
    }
}

/**
 * KeyStatus describes whether a key is configured and where it comes from.
 */
export class KeyStatus {
    /**
     * Creates a new KeyStatus instance.
     * @param {Partial<KeyStatus>} [$$source = {}] - The source object to create the KeyStatus.
     */
    constructor($$source = {}) {
        if (!("is_set" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_set"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * "env", "keyring", or "none"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyStatus(/** @type {Partial<KeyStatus>} */($$parsedSource));
    }
}

/**
 * Provider holds non-secret configuration for AI providers.
 * API keys are stored in the OS keyring, NOT here.
 * OllamaURL and AWSRegion are non-secret and remain in settings.
 */
export class Provider {
    /**
     * Creates a new Provider instance.
     * @param {Partial<Provider>} [$$source = {}] - The source object to create the Provider.
     */
    constructor($$source = {}) {
        if (!("ollama_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ollama_url"] = "";
        }
        if (!("aws_region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["aws_region"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Provider}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Provider(/** @type {Partial<Provider>} */($$parsedSource));
    }
}

/**
 * Settings is the top-level application settings structure persisted to disk.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("active_provider" in $$source)) {
            /**
             * "openai" | "claude" | "ollama" | "bedrock"
             * @member
             * @type {string}
             */
            this["active_provider"] = "";
        }
        if (!("providers" in $$source)) {
            /**
             * @member
             * @type {Provider}
             */
            this["providers"] = (new Provider());
        }
        if (!("shortcut_key" in $$source)) {
            /**
             * LEGACY — migrated to ShortcutFix on load
             * @member
             * @type {string}
             */
            this["shortcut_key"] = "";
        }
        if (!("shortcut_mode" in $$source)) {
            /**
             * "double_tap" | "independent"
             * @member
             * @type {string}
             */
            this["shortcut_mode"] = "";
        }
        if (!("shortcut_fix" in $$source)) {
            /**
             * e.g. "ctrl+g"
             * @member
             * @type {string}
             */
            this["shortcut_fix"] = "";
        }
        if (!("shortcut_pyramidize" in $$source)) {
            /**
             * e.g. "ctrl+shift+g" (independent mode only)
             * @member
             * @type {string}
             */
            this["shortcut_pyramidize"] = "";
        }
        if (!("shortcut_double_tap_delay" in $$source)) {
            /**
             * ms, 100-500, default 200
             * @member
             * @type {number}
             */
            this["shortcut_double_tap_delay"] = 0;
        }
        if (!("start_on_boot" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["start_on_boot"] = false;
        }
        if (!("theme_preference" in $$source)) {
            /**
             * "light" | "dark" | "system"
             * @member
             * @type {string}
             */
            this["theme_preference"] = "";
        }
        if (!("completed_setup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed_setup"] = false;
        }
        if (!("log_level" in $$source)) {
            /**
             * "off"|"trace"|"debug"|"info"|"warning"|"error"
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }
        if (!("sensitive_logging" in $$source)) {
            /**
             * logs full API payloads; never share the log file while enabled
             * @member
             * @type {boolean}
             */
            this["sensitive_logging"] = false;
        }
        if (!("update_channel" in $$source)) {
            /**
             * "" (auto-detect), "stable", or "pre-release"
             * @member
             * @type {string}
             */
            this["update_channel"] = "";
        }
        if (!("app_presets" in $$source)) {
            /**
             * Pyramidize settings
             * @member
             * @type {AppPreset[]}
             */
            this["app_presets"] = [];
        }
        if (!("pyramidize_quality_threshold" in $$source)) {
            /**
             * default 0.65
             * @member
             * @type {number}
             */
            this["pyramidize_quality_threshold"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField1_0($$parsedSource["providers"]);
        }
        if ("app_presets" in $$parsedSource) {
            $$parsedSource["app_presets"] = $$createField13_0($$parsedSource["app_presets"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Provider.createFrom;
const $$createType1 = AppPreset.createFrom;
const $$createType2 = $Create.Array($$createType1);
