// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service handles loading and saving application settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llm$0 from "../../llm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteKey removes an API key for the given provider from the OS keyring.
 * @param {string} provider
 * @returns {$CancellablePromise<void>}
 */
export function DeleteKey(provider) {
    return $Call.ByID(3023780468, provider);
}

/**
 * Get returns a copy of the current settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function Get() {
    return $Call.ByID(2040733582).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetClaudeCodeStatus reports whether the Claude Code CLI is installed on this
 * machine and signed in, so the UI can offer it as a provider that needs no API
 * key. Signing in happens in the user's own terminal through Anthropic's flow —
 * KeyLint only looks, and never reads or stores credentials.
 * @returns {$CancellablePromise<llm$0.ClaudeCodeStatus>}
 */
export function GetClaudeCodeStatus() {
    return $Call.ByID(3561813659).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetKey returns the API key for the given provider.
 * Priority: environment variable → OS keyring.
 * Returns empty string if not configured.
 * @param {string} provider
 * @returns {$CancellablePromise<string>}
 */
export function GetKey(provider) {
    return $Call.ByID(3739301461, provider);
}

/**
 * GetKeyStatus returns whether an API key is configured for the given provider,
 * and where it comes from ("env", "keyring", or "none").
 * @param {string} provider
 * @returns {$CancellablePromise<$models.KeyStatus>}
 */
export function GetKeyStatus(provider) {
    return $Call.ByID(1645967871, provider).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListModels returns the models a provider can serve, cached per provider.
 * 
 * It never returns an error: a provider that cannot be reached, one with no key
 * and one whose listing this app cannot use all yield the built-in list, and a
 * provider that listed nothing yields an empty one. ModelList.Source says which
 * happened, so the picker can explain itself; ttl decides how long that answer
 * is worth keeping.
 * @param {string} provider
 * @returns {$CancellablePromise<llm$0.ModelList>}
 */
export function ListModels(provider) {
    return $Call.ByID(3734180264, provider).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ResetToDefaults resets settings to their default values and saves to disk.
 * @returns {$CancellablePromise<void>}
 */
export function ResetToDefaults() {
    return $Call.ByID(2262468238);
}

/**
 * Save persists the provided settings to disk.
 * @param {$models.Settings} updated
 * @returns {$CancellablePromise<void>}
 */
export function Save(updated) {
    return $Call.ByID(3744916527, updated);
}

/**
 * SetKey stores an API key for the given provider in the OS keyring.
 * Returns an error if the keyring is unavailable on this platform.
 * @param {string} provider
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetKey(provider, key) {
    return $Call.ByID(3799725721, provider, key);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
const $$createType1 = llm$0.ClaudeCodeStatus.createFrom;
const $$createType2 = $models.KeyStatus.createFrom;
const $$createType3 = llm$0.ModelList.createFrom;
