// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service forwards frontend log messages into the Go structured logger.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Log writes a frontend message at the given level into debug.log.
 * The msg is wrapped in Redact() because frontend messages may contain user text.
 * Error and warn levels log the msg directly (operational).
 * @param {string} level
 * @param {string} msg
 * @returns {$CancellablePromise<void>}
 */
export function Log(level, msg) {
    return $Call.ByID(972304125, level, msg);
}
