// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Notice is one notification, and what KeyLint shows when it is clicked.
 * 
 * Title and Body are all the notification itself carries: Windows keeps
 * toasts in the Action Center's database on disk, so they never contain the
 * user's text. Detail, Input and Output stay in memory and reach only the Fix
 * page.
 */
export class Notice {
    /**
     * Creates a new Notice instance.
     * @param {Partial<Notice>} [$$source = {}] - The source object to create the Notice.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {Target}
             */
            this["target"] = Target.$zero;
        }
        if (!("detail" in $$source)) {
            /**
             * Detail is the full error, as the Fix page would have shown it.
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("input" in $$source)) {
            /**
             * Input is the text the fix ran on; Output what it produced, if it got
             * that far. Either may be empty.
             * @member
             * @type {string}
             */
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Notice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Notice(/** @type {Partial<Notice>} */($$parsedSource));
    }
}

/**
 * Target is where a click on a notification takes the user.
 * @readonly
 * @enum {string}
 */
export const Target = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * TargetProviders is Settings › AI Providers: the key, the CLI sign-in or
     * the model is what needs fixing.
     */
    TargetProviders: "providers",

    /**
     * TargetFix is the Fix page, showing what happened and the text involved.
     */
    TargetFix: "fix",
};
