// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service handles first-run detection and setup completion.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CompleteSetup marks the setup wizard as done.
 * 
 * Through settings.Update, so a save that lands meanwhile (a provider switch)
 * is not overwritten by settings read before it.
 * @returns {$CancellablePromise<void>}
 */
export function CompleteSetup() {
    return $Call.ByID(2084461659);
}

/**
 * IsFirstRun reports whether the setup wizard should open.
 * 
 * Only for someone with nothing usable: completed_setup unset AND no API key
 * for any provider (env or keyring), no signed-in Claude Code CLI, and no
 * saved active provider that can work. Anyone with something usable is never
 * asked for it again — their setup is marked complete here, silently, and the
 * log line says why. The flag alone is not trusted to mean "new user": it has
 * been seen false on a machine whose keys and CLI were all in place.
 * 
 * Never returns or logs a key's value: only whether one is set. (On the way,
 * GetKeyStatus fetches it from the keyring and drops it.)
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFirstRun() {
    return $Call.ByID(2551651914);
}
